###############-VERSION-###################
version: '3.7'

################-SERVICIOS-################
services:

###################-CLIENTE-###########################
   cliente:
    build: ./HW1/src/cli
    depends_on:
        - postgres
        - servidor
    ports:
        - "8080:8080"

###################-SERVIDOR-#########################   
   servidor:
    build: ./HW1/src/server
    depends_on:
        - postgres

###################-GRPC-#############################  
   g_rpc:
    build: ./HW1/src/GRPC
    restart: always
    depends_on:
        - servidor
        - cliente
    ports:
        - "8050:8050"
    
#################-POSTGRES-##########################
   postgres:
    image: docker.io/bitnami/postgresql:11
    volumes:
        - ./HW1/src/database/init.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
        - POSTGRESQL_USER=postgres
        - POSTGRESQL_DATABASE=tiendita
        - ALLOW_EMPTY_PASSWORD=yes
        - POSTGRESQL_PASSWORD=marihuana
  
######################-REDIS-##########################
   redis_cache:
    image: docker.io/bitnami/redis:latest
    volumes:
        - ./HW1/redis.conf:/usr/local/etc/redis/redis.conf
    environment:
        - ALLOW_EMPTY_PASSWORD=yes



##################-OTRAS-PRUEBAS-###################

#################################################    
#   caching:
#    image: bitnami/redis:6.0.16
#    restart: always
#    environment:
#      - ALLOW_EMPTY_PASSWORD=yes
#    volumes:
#     - ./data/redis:/bitnami/redis/data
#    ports:
#      - "6379:3000"

  